# Generated by Django 5.2 on 2025-06-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="serial_number",
            field=models.CharField(default="e7cc30e8", max_length=20, unique=True),
        ),
    ]
