# Generated by Django 5.1.6 on 2025-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_user_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(default='4bd5f210', max_length=20, unique=True),
        ),
    ]
