# Generated by Django 5.1.6 on 2025-03-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_patient_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(blank=True, default='d5a516a6', max_length=20, null=True, unique=True),
        ),
    ]
