# Generated by Django 5.1.6 on 2025-03-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_patient_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='login_status',
            field=models.CharField(default='offline', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(blank=True, default='ac7d4e36', max_length=20, null=True, unique=True),
        ),
    ]
