# Generated by Django 5.1.6 on 2025-03-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_patient_login_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(blank=True, default='53f4cc41', max_length=20, null=True),
        ),
    ]
