# Generated by Django 5.1.6 on 2025-03-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_alter_patient_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(default='68cc888f', max_length=20, unique=True),
        ),
    ]
