# Generated by Django 5.1.6 on 2025-04-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_blacklistedaccesstoken_alter_patient_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(default='f1618be3', max_length=20, unique=True),
        ),
    ]
