# Generated by Django 5.1.6 on 2025-04-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_alter_patient_serial_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlacklistedAccessToken',
            new_name='BlacklistedAccess',
        ),
        migrations.AlterField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(default='415b3186', max_length=20, unique=True),
        ),
    ]
