# Generated by Django 5.1.6 on 2025-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_rename_blacklistedaccesstoken_blacklistedaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(default='8550f15d', max_length=20, unique=True),
        ),
    ]
