# Generated by Django 5.1.6 on 2025-04-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_alter_patient_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(default='1e11f3b4', max_length=20, unique=True),
        ),
    ]
