# Generated by Django 5.2 on 2025-05-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testorder',
            name='prescription_test',
        ),
        migrations.AddField(
            model_name='testorder',
            name='prescription_testt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription_test'),
        ),
    ]
