# Generated by Django 5.2 on 2025-05-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_testorder_prescription_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testorder',
            old_name='prescription_testt',
            new_name='prescription_test',
        ),
    ]
