# Generated by Django 5.2 on 2025-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_prescription_test_purchased"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription_test",
            name="purchased",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
