# Generated by Django 5.2 on 2025-05-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_rename_prescription_testt_testorder_prescription_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testorder',
            name='prescription_test',
        ),
        migrations.AddField(
            model_name='testorder',
            name='prescription_test',
            field=models.ManyToManyField(blank=True, null=True, to='doctor.prescription_test'),
        ),
    ]
