# Generated by Django 5.2 on 2025-06-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_alter_prescription_test_purchased"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription_test",
            name="purchased",
            field=models.CharField(
                blank=True, default="pending", max_length=200, null=True
            ),
        ),
    ]
