# Generated by Django 5.2 on 2025-05-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_testorder_prescription_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='prescription_test',
            field=models.ManyToManyField(to='doctor.prescription_test'),
        ),
    ]
