# Generated by Django 5.2 on 2025-05-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_remove_testorder_prescription_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='days',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_description',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='relation_with_meal',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='test_description',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='time',
        ),
    ]
