# Generated by Django 5.1.6 on 2025-03-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, max_length=200, null=True),
        ),
    ]
