# Generated by Django 5.1.6 on 2025-04-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0046_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_information',
            name='register_status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
