# Generated by Django 5.1.6 on 2025-04-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0047_alter_doctor_information_register_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='PAYMENT_status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='pending', max_length=200),
        ),
    ]
